version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "13:00"
  open-pull-requests-limit: 10
  reviewers:
  - kahwee
  assignees:
  - kahwee
  ignore:
  - dependency-name: styletron-engine-atomic
    versions:
    - 1.4.7
  - dependency-name: emotion-theming
    versions:
    - 11.0.0
  - dependency-name: flow-bin
    versions:
    - 0.141.0
    - 0.143.1
    - 0.144.0
    - 0.145.0
  - dependency-name: react-select
    versions:
    - 4.1.0
  - dependency-name: "@storybook/addon-docs"
    versions:
    - 6.1.20
  - dependency-name: eslint
    versions:
    - 7.16.0
    - 7.21.0
  - dependency-name: husky
    versions:
    - 5.1.2
  - dependency-name: lodash
    versions:
    - 4.17.21
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.2
    - 11.2.3
    - 11.2.5
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
  - dependency-name: "@babel/preset-react"
    versions:
    - 7.12.10
    - 7.12.13
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: "@storybook/addons"
    versions:
    - 6.1.11
    - 6.1.15
  - dependency-name: "@storybook/react"
    versions:
    - 6.1.11
    - 6.1.15
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.3
