// flow-typed signature: 57ace7b8a834e7de0d23f0aed697f931
// flow-typed version: <<STUB>>/babel-plugin-transform-styletron-display-name_v^1.1.4/flow_v0.107.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-styletron-display-name'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-styletron-display-name' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-styletron-display-name/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-styletron-display-name/src/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-styletron-display-name/src/index'>;
}
