// flow-typed signature: a0005f7c6b20a6de01259a6555de4a6a
// flow-typed version: <<STUB>>/babel-plugin-transform-styletron-display-name_v^1.1.3/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-styletron-display-name'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-styletron-display-name' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-styletron-display-name/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-styletron-display-name/src/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-styletron-display-name/src/index'>;
}
