// flow-typed signature: 1de2abdd4d86ca5c9b8e6efa78c91d42
// flow-typed version: <<STUB>>/create-universal-package_v^4.1.1/flow_v0.110.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'create-universal-package'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'create-universal-package' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'create-universal-package/bin/build' {
  declare module.exports: any;
}

declare module 'create-universal-package/bin/clean' {
  declare module.exports: any;
}

declare module 'create-universal-package/bin' {
  declare module.exports: any;
}

declare module 'create-universal-package/build' {
  declare module.exports: any;
}

declare module 'create-universal-package/clean' {
  declare module.exports: any;
}

declare module 'create-universal-package/preflight' {
  declare module.exports: any;
}

declare module 'create-universal-package/worker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'create-universal-package/bin/build.js' {
  declare module.exports: $Exports<'create-universal-package/bin/build'>;
}
declare module 'create-universal-package/bin/clean.js' {
  declare module.exports: $Exports<'create-universal-package/bin/clean'>;
}
declare module 'create-universal-package/bin/index' {
  declare module.exports: $Exports<'create-universal-package/bin'>;
}
declare module 'create-universal-package/bin/index.js' {
  declare module.exports: $Exports<'create-universal-package/bin'>;
}
declare module 'create-universal-package/build.js' {
  declare module.exports: $Exports<'create-universal-package/build'>;
}
declare module 'create-universal-package/clean.js' {
  declare module.exports: $Exports<'create-universal-package/clean'>;
}
declare module 'create-universal-package/preflight.js' {
  declare module.exports: $Exports<'create-universal-package/preflight'>;
}
declare module 'create-universal-package/worker.js' {
  declare module.exports: $Exports<'create-universal-package/worker'>;
}
