// flow-typed signature: c44bcd7eb8b7ecc69c4d955fc5ffa64e
// flow-typed version: <<STUB>>/create-universal-package_v^3.4.6/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'create-universal-package'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'create-universal-package' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'create-universal-package/bin/build-tests' {
  declare module.exports: any;
}

declare module 'create-universal-package/bin/build' {
  declare module.exports: any;
}

declare module 'create-universal-package/bin/clean' {
  declare module.exports: any;
}

declare module 'create-universal-package/bin/index' {
  declare module.exports: any;
}

declare module 'create-universal-package/bin/logger-ci' {
  declare module.exports: any;
}

declare module 'create-universal-package/bin/logger' {
  declare module.exports: any;
}

declare module 'create-universal-package/lib/build' {
  declare module.exports: any;
}

declare module 'create-universal-package/lib/rollup-loader' {
  declare module.exports: any;
}

declare module 'create-universal-package/lib/rollup-plugin-babel' {
  declare module.exports: any;
}

declare module 'create-universal-package/lib/rollup-plugin-memory' {
  declare module.exports: any;
}

declare module 'create-universal-package/lib/tasks/build-browser' {
  declare module.exports: any;
}

declare module 'create-universal-package/lib/tasks/build' {
  declare module.exports: any;
}

declare module 'create-universal-package/lib/tasks/clean' {
  declare module.exports: any;
}

declare module 'create-universal-package/lib/tasks/gen-flow-libdef' {
  declare module.exports: any;
}

declare module 'create-universal-package/lib/tasks/preflight' {
  declare module.exports: any;
}

declare module 'create-universal-package/lib/validate-config' {
  declare module.exports: any;
}

declare module 'create-universal-package/lib/worker' {
  declare module.exports: any;
}

declare module 'create-universal-package/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'create-universal-package/bin/build-tests.js' {
  declare module.exports: $Exports<'create-universal-package/bin/build-tests'>;
}
declare module 'create-universal-package/bin/build.js' {
  declare module.exports: $Exports<'create-universal-package/bin/build'>;
}
declare module 'create-universal-package/bin/clean.js' {
  declare module.exports: $Exports<'create-universal-package/bin/clean'>;
}
declare module 'create-universal-package/bin/index.js' {
  declare module.exports: $Exports<'create-universal-package/bin/index'>;
}
declare module 'create-universal-package/bin/logger-ci.js' {
  declare module.exports: $Exports<'create-universal-package/bin/logger-ci'>;
}
declare module 'create-universal-package/bin/logger.js' {
  declare module.exports: $Exports<'create-universal-package/bin/logger'>;
}
declare module 'create-universal-package/lib/build.js' {
  declare module.exports: $Exports<'create-universal-package/lib/build'>;
}
declare module 'create-universal-package/lib/rollup-loader.js' {
  declare module.exports: $Exports<'create-universal-package/lib/rollup-loader'>;
}
declare module 'create-universal-package/lib/rollup-plugin-babel.js' {
  declare module.exports: $Exports<'create-universal-package/lib/rollup-plugin-babel'>;
}
declare module 'create-universal-package/lib/rollup-plugin-memory.js' {
  declare module.exports: $Exports<'create-universal-package/lib/rollup-plugin-memory'>;
}
declare module 'create-universal-package/lib/tasks/build-browser.js' {
  declare module.exports: $Exports<'create-universal-package/lib/tasks/build-browser'>;
}
declare module 'create-universal-package/lib/tasks/build.js' {
  declare module.exports: $Exports<'create-universal-package/lib/tasks/build'>;
}
declare module 'create-universal-package/lib/tasks/clean.js' {
  declare module.exports: $Exports<'create-universal-package/lib/tasks/clean'>;
}
declare module 'create-universal-package/lib/tasks/gen-flow-libdef.js' {
  declare module.exports: $Exports<'create-universal-package/lib/tasks/gen-flow-libdef'>;
}
declare module 'create-universal-package/lib/tasks/preflight.js' {
  declare module.exports: $Exports<'create-universal-package/lib/tasks/preflight'>;
}
declare module 'create-universal-package/lib/validate-config.js' {
  declare module.exports: $Exports<'create-universal-package/lib/validate-config'>;
}
declare module 'create-universal-package/lib/worker.js' {
  declare module.exports: $Exports<'create-universal-package/lib/worker'>;
}
declare module 'create-universal-package/test/index.js' {
  declare module.exports: $Exports<'create-universal-package/test/index'>;
}
