// flow-typed signature: f3fb6a15c0ae5ed9c051f8a12971337b
// flow-typed version: <<STUB>>/eslint-plugin-sort-imports-es6-autofix_v^0.5.0/flow_v0.110.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-sort-imports-es6-autofix'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-sort-imports-es6-autofix' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-sort-imports-es6-autofix/rules/sort-imports-es6' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-sort-imports-es6-autofix/index' {
  declare module.exports: $Exports<'eslint-plugin-sort-imports-es6-autofix'>;
}
declare module 'eslint-plugin-sort-imports-es6-autofix/index.js' {
  declare module.exports: $Exports<'eslint-plugin-sort-imports-es6-autofix'>;
}
declare module 'eslint-plugin-sort-imports-es6-autofix/rules/sort-imports-es6.js' {
  declare module.exports: $Exports<'eslint-plugin-sort-imports-es6-autofix/rules/sort-imports-es6'>;
}
