// flow-typed signature: 6375e9e11256ff47b2e22d4d0d721cc0
// flow-typed version: <<STUB>>/eslint-plugin-baseui_v^9.103.0/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-baseui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-baseui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-baseui/__tests__/config.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-baseui/__tests__/deprecated-component-api.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-baseui/__tests__/deprecated-theme-api-test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-baseui/__tests__/example-config/fixture' {
  declare module.exports: any;
}

declare module 'eslint-plugin-baseui/__tests__/example-config/node_modules/eslint-plugin-baseui' {
  declare module.exports: any;
}

declare module 'eslint-plugin-baseui/__tests__/no-deep-imports' {
  declare module.exports: any;
}

declare module 'eslint-plugin-baseui/src/deprecated-component-api' {
  declare module.exports: any;
}

declare module 'eslint-plugin-baseui/src/deprecated-theme-api' {
  declare module.exports: any;
}

declare module 'eslint-plugin-baseui/src' {
  declare module.exports: any;
}

declare module 'eslint-plugin-baseui/src/messages' {
  declare module.exports: any;
}

declare module 'eslint-plugin-baseui/src/no-deep-imports' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-baseui/__tests__/config.test.js' {
  declare module.exports: $Exports<'eslint-plugin-baseui/__tests__/config.test'>;
}
declare module 'eslint-plugin-baseui/__tests__/deprecated-component-api.test.js' {
  declare module.exports: $Exports<'eslint-plugin-baseui/__tests__/deprecated-component-api.test'>;
}
declare module 'eslint-plugin-baseui/__tests__/deprecated-theme-api-test.js' {
  declare module.exports: $Exports<'eslint-plugin-baseui/__tests__/deprecated-theme-api-test'>;
}
declare module 'eslint-plugin-baseui/__tests__/example-config/fixture.js' {
  declare module.exports: $Exports<'eslint-plugin-baseui/__tests__/example-config/fixture'>;
}
declare module 'eslint-plugin-baseui/__tests__/example-config/node_modules/eslint-plugin-baseui/index' {
  declare module.exports: $Exports<'eslint-plugin-baseui/__tests__/example-config/node_modules/eslint-plugin-baseui'>;
}
declare module 'eslint-plugin-baseui/__tests__/example-config/node_modules/eslint-plugin-baseui/index.js' {
  declare module.exports: $Exports<'eslint-plugin-baseui/__tests__/example-config/node_modules/eslint-plugin-baseui'>;
}
declare module 'eslint-plugin-baseui/__tests__/no-deep-imports.js' {
  declare module.exports: $Exports<'eslint-plugin-baseui/__tests__/no-deep-imports'>;
}
declare module 'eslint-plugin-baseui/index' {
  declare module.exports: $Exports<'eslint-plugin-baseui'>;
}
declare module 'eslint-plugin-baseui/index.js' {
  declare module.exports: $Exports<'eslint-plugin-baseui'>;
}
declare module 'eslint-plugin-baseui/src/deprecated-component-api.js' {
  declare module.exports: $Exports<'eslint-plugin-baseui/src/deprecated-component-api'>;
}
declare module 'eslint-plugin-baseui/src/deprecated-theme-api.js' {
  declare module.exports: $Exports<'eslint-plugin-baseui/src/deprecated-theme-api'>;
}
declare module 'eslint-plugin-baseui/src/index' {
  declare module.exports: $Exports<'eslint-plugin-baseui/src'>;
}
declare module 'eslint-plugin-baseui/src/index.js' {
  declare module.exports: $Exports<'eslint-plugin-baseui/src'>;
}
declare module 'eslint-plugin-baseui/src/messages.js' {
  declare module.exports: $Exports<'eslint-plugin-baseui/src/messages'>;
}
declare module 'eslint-plugin-baseui/src/no-deep-imports.js' {
  declare module.exports: $Exports<'eslint-plugin-baseui/src/no-deep-imports'>;
}
