// flow-typed signature: 78af4fccc07672fc9ef468c86f61a79a
// flow-typed version: <<STUB>>/flow-copy-source_v^2.0.7/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flow-copy-source'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flow-copy-source' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flow-copy-source/bin/flow-copy-source' {
  declare module.exports: any;
}

declare module 'flow-copy-source/src/index' {
  declare module.exports: any;
}

declare module 'flow-copy-source/src/kefir-copy-file' {
  declare module.exports: any;
}

declare module 'flow-copy-source/src/kefir-glob' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flow-copy-source/bin/flow-copy-source.js' {
  declare module.exports: $Exports<'flow-copy-source/bin/flow-copy-source'>;
}
declare module 'flow-copy-source/src/index.js' {
  declare module.exports: $Exports<'flow-copy-source/src/index'>;
}
declare module 'flow-copy-source/src/kefir-copy-file.js' {
  declare module.exports: $Exports<'flow-copy-source/src/kefir-copy-file'>;
}
declare module 'flow-copy-source/src/kefir-glob.js' {
  declare module.exports: $Exports<'flow-copy-source/src/kefir-glob'>;
}
