// flow-typed signature: 573829223c618f6ceca29f9b330887e4
// flow-typed version: <<STUB>>/husky_v^5.1.3/flow_v0.110.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'husky'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'husky' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'husky/lib/bin' {
  declare module.exports: any;
}

declare module 'husky/lib/commands/add' {
  declare module.exports: any;
}

declare module 'husky/lib/commands/init' {
  declare module.exports: any;
}

declare module 'husky/lib/commands/install' {
  declare module.exports: any;
}

declare module 'husky/lib/commands/uninstall' {
  declare module.exports: any;
}

// Filename aliases
declare module 'husky/lib/bin.js' {
  declare module.exports: $Exports<'husky/lib/bin'>;
}
declare module 'husky/lib/commands/add.js' {
  declare module.exports: $Exports<'husky/lib/commands/add'>;
}
declare module 'husky/lib/commands/init.js' {
  declare module.exports: $Exports<'husky/lib/commands/init'>;
}
declare module 'husky/lib/commands/install.js' {
  declare module.exports: $Exports<'husky/lib/commands/install'>;
}
declare module 'husky/lib/commands/uninstall.js' {
  declare module.exports: $Exports<'husky/lib/commands/uninstall'>;
}
