// flow-typed signature: 752c5865799ad0708e642bae5bbb6d32
// flow-typed version: <<STUB>>/jest-extended_v^0.11.2/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-extended'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-extended' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-extended/dist/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeAfter/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeAfter/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeArray/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeArray/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeArrayOfSize/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeArrayOfSize/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeBefore/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeBefore/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeBoolean/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeBoolean/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeDate/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeDate/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeEmpty/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeEmpty/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeEven/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeEven/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeExtensible/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeExtensible/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeFalse/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeFalse/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeFinite/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeFinite/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeFrozen/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeFrozen/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeFunction/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeFunction/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeHexadecimal/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeHexadecimal/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeNaN/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeNaN/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeNegative/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeNegative/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeNil/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeNil/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeNumber/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeNumber/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeObject/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeObject/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeOdd/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeOdd/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeOneOf/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeOneOf/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBePositive/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBePositive/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeSealed/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeSealed/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeString/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeString/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeTrue/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeTrue/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeValidDate/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeValidDate/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeWithin/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toBeWithin/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toContainAllEntries/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toContainAllEntries/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toContainAllKeys/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toContainAllKeys/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toContainAllValues/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toContainAllValues/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toContainAnyEntries/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toContainAnyEntries/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toContainAnyKeys/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toContainAnyKeys/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toContainAnyValues/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toContainAnyValues/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toContainEntries/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toContainEntries/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toContainEntry/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toContainEntry/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toContainKey/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toContainKey/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toContainKeys/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toContainKeys/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toContainValue/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toContainValue/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toContainValues/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toContainValues/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toEndWith/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toEndWith/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toEqualCaseInsensitive/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toEqualCaseInsensitive/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toHaveBeenCalledAfter/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toHaveBeenCalledAfter/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toHaveBeenCalledBefore/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toHaveBeenCalledBefore/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toInclude/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toInclude/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toIncludeAllMembers/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toIncludeAllMembers/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toIncludeAnyMembers/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toIncludeAnyMembers/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toIncludeMultiple/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toIncludeMultiple/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toIncludeRepeated/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toIncludeRepeated/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toIncludeSameMembers/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toIncludeSameMembers/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toReject/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toReject/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toResolve/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toResolve/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toSatisfy/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toSatisfyAll/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toSatisfyAll/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toStartWith/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toStartWith/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toThrowWithMessage/index' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/matchers/toThrowWithMessage/predicate' {
  declare module.exports: any;
}

declare module 'jest-extended/dist/utils/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-extended/dist/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/index'>;
}
declare module 'jest-extended/dist/matchers/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/index'>;
}
declare module 'jest-extended/dist/matchers/toBeAfter/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeAfter/index'>;
}
declare module 'jest-extended/dist/matchers/toBeAfter/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeAfter/predicate'>;
}
declare module 'jest-extended/dist/matchers/toBeArray/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeArray/index'>;
}
declare module 'jest-extended/dist/matchers/toBeArray/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeArray/predicate'>;
}
declare module 'jest-extended/dist/matchers/toBeArrayOfSize/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeArrayOfSize/index'>;
}
declare module 'jest-extended/dist/matchers/toBeArrayOfSize/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeArrayOfSize/predicate'>;
}
declare module 'jest-extended/dist/matchers/toBeBefore/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeBefore/index'>;
}
declare module 'jest-extended/dist/matchers/toBeBefore/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeBefore/predicate'>;
}
declare module 'jest-extended/dist/matchers/toBeBoolean/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeBoolean/index'>;
}
declare module 'jest-extended/dist/matchers/toBeBoolean/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeBoolean/predicate'>;
}
declare module 'jest-extended/dist/matchers/toBeDate/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeDate/index'>;
}
declare module 'jest-extended/dist/matchers/toBeDate/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeDate/predicate'>;
}
declare module 'jest-extended/dist/matchers/toBeEmpty/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeEmpty/index'>;
}
declare module 'jest-extended/dist/matchers/toBeEmpty/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeEmpty/predicate'>;
}
declare module 'jest-extended/dist/matchers/toBeEven/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeEven/index'>;
}
declare module 'jest-extended/dist/matchers/toBeEven/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeEven/predicate'>;
}
declare module 'jest-extended/dist/matchers/toBeExtensible/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeExtensible/index'>;
}
declare module 'jest-extended/dist/matchers/toBeExtensible/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeExtensible/predicate'>;
}
declare module 'jest-extended/dist/matchers/toBeFalse/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeFalse/index'>;
}
declare module 'jest-extended/dist/matchers/toBeFalse/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeFalse/predicate'>;
}
declare module 'jest-extended/dist/matchers/toBeFinite/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeFinite/index'>;
}
declare module 'jest-extended/dist/matchers/toBeFinite/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeFinite/predicate'>;
}
declare module 'jest-extended/dist/matchers/toBeFrozen/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeFrozen/index'>;
}
declare module 'jest-extended/dist/matchers/toBeFrozen/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeFrozen/predicate'>;
}
declare module 'jest-extended/dist/matchers/toBeFunction/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeFunction/index'>;
}
declare module 'jest-extended/dist/matchers/toBeFunction/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeFunction/predicate'>;
}
declare module 'jest-extended/dist/matchers/toBeHexadecimal/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeHexadecimal/index'>;
}
declare module 'jest-extended/dist/matchers/toBeHexadecimal/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeHexadecimal/predicate'>;
}
declare module 'jest-extended/dist/matchers/toBeNaN/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeNaN/index'>;
}
declare module 'jest-extended/dist/matchers/toBeNaN/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeNaN/predicate'>;
}
declare module 'jest-extended/dist/matchers/toBeNegative/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeNegative/index'>;
}
declare module 'jest-extended/dist/matchers/toBeNegative/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeNegative/predicate'>;
}
declare module 'jest-extended/dist/matchers/toBeNil/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeNil/index'>;
}
declare module 'jest-extended/dist/matchers/toBeNil/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeNil/predicate'>;
}
declare module 'jest-extended/dist/matchers/toBeNumber/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeNumber/index'>;
}
declare module 'jest-extended/dist/matchers/toBeNumber/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeNumber/predicate'>;
}
declare module 'jest-extended/dist/matchers/toBeObject/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeObject/index'>;
}
declare module 'jest-extended/dist/matchers/toBeObject/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeObject/predicate'>;
}
declare module 'jest-extended/dist/matchers/toBeOdd/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeOdd/index'>;
}
declare module 'jest-extended/dist/matchers/toBeOdd/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeOdd/predicate'>;
}
declare module 'jest-extended/dist/matchers/toBeOneOf/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeOneOf/index'>;
}
declare module 'jest-extended/dist/matchers/toBeOneOf/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeOneOf/predicate'>;
}
declare module 'jest-extended/dist/matchers/toBePositive/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBePositive/index'>;
}
declare module 'jest-extended/dist/matchers/toBePositive/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBePositive/predicate'>;
}
declare module 'jest-extended/dist/matchers/toBeSealed/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeSealed/index'>;
}
declare module 'jest-extended/dist/matchers/toBeSealed/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeSealed/predicate'>;
}
declare module 'jest-extended/dist/matchers/toBeString/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeString/index'>;
}
declare module 'jest-extended/dist/matchers/toBeString/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeString/predicate'>;
}
declare module 'jest-extended/dist/matchers/toBeTrue/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeTrue/index'>;
}
declare module 'jest-extended/dist/matchers/toBeTrue/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeTrue/predicate'>;
}
declare module 'jest-extended/dist/matchers/toBeValidDate/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeValidDate/index'>;
}
declare module 'jest-extended/dist/matchers/toBeValidDate/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeValidDate/predicate'>;
}
declare module 'jest-extended/dist/matchers/toBeWithin/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeWithin/index'>;
}
declare module 'jest-extended/dist/matchers/toBeWithin/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toBeWithin/predicate'>;
}
declare module 'jest-extended/dist/matchers/toContainAllEntries/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toContainAllEntries/index'>;
}
declare module 'jest-extended/dist/matchers/toContainAllEntries/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toContainAllEntries/predicate'>;
}
declare module 'jest-extended/dist/matchers/toContainAllKeys/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toContainAllKeys/index'>;
}
declare module 'jest-extended/dist/matchers/toContainAllKeys/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toContainAllKeys/predicate'>;
}
declare module 'jest-extended/dist/matchers/toContainAllValues/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toContainAllValues/index'>;
}
declare module 'jest-extended/dist/matchers/toContainAllValues/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toContainAllValues/predicate'>;
}
declare module 'jest-extended/dist/matchers/toContainAnyEntries/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toContainAnyEntries/index'>;
}
declare module 'jest-extended/dist/matchers/toContainAnyEntries/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toContainAnyEntries/predicate'>;
}
declare module 'jest-extended/dist/matchers/toContainAnyKeys/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toContainAnyKeys/index'>;
}
declare module 'jest-extended/dist/matchers/toContainAnyKeys/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toContainAnyKeys/predicate'>;
}
declare module 'jest-extended/dist/matchers/toContainAnyValues/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toContainAnyValues/index'>;
}
declare module 'jest-extended/dist/matchers/toContainAnyValues/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toContainAnyValues/predicate'>;
}
declare module 'jest-extended/dist/matchers/toContainEntries/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toContainEntries/index'>;
}
declare module 'jest-extended/dist/matchers/toContainEntries/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toContainEntries/predicate'>;
}
declare module 'jest-extended/dist/matchers/toContainEntry/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toContainEntry/index'>;
}
declare module 'jest-extended/dist/matchers/toContainEntry/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toContainEntry/predicate'>;
}
declare module 'jest-extended/dist/matchers/toContainKey/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toContainKey/index'>;
}
declare module 'jest-extended/dist/matchers/toContainKey/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toContainKey/predicate'>;
}
declare module 'jest-extended/dist/matchers/toContainKeys/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toContainKeys/index'>;
}
declare module 'jest-extended/dist/matchers/toContainKeys/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toContainKeys/predicate'>;
}
declare module 'jest-extended/dist/matchers/toContainValue/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toContainValue/index'>;
}
declare module 'jest-extended/dist/matchers/toContainValue/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toContainValue/predicate'>;
}
declare module 'jest-extended/dist/matchers/toContainValues/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toContainValues/index'>;
}
declare module 'jest-extended/dist/matchers/toContainValues/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toContainValues/predicate'>;
}
declare module 'jest-extended/dist/matchers/toEndWith/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toEndWith/index'>;
}
declare module 'jest-extended/dist/matchers/toEndWith/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toEndWith/predicate'>;
}
declare module 'jest-extended/dist/matchers/toEqualCaseInsensitive/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toEqualCaseInsensitive/index'>;
}
declare module 'jest-extended/dist/matchers/toEqualCaseInsensitive/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toEqualCaseInsensitive/predicate'>;
}
declare module 'jest-extended/dist/matchers/toHaveBeenCalledAfter/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toHaveBeenCalledAfter/index'>;
}
declare module 'jest-extended/dist/matchers/toHaveBeenCalledAfter/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toHaveBeenCalledAfter/predicate'>;
}
declare module 'jest-extended/dist/matchers/toHaveBeenCalledBefore/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toHaveBeenCalledBefore/index'>;
}
declare module 'jest-extended/dist/matchers/toHaveBeenCalledBefore/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toHaveBeenCalledBefore/predicate'>;
}
declare module 'jest-extended/dist/matchers/toInclude/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toInclude/index'>;
}
declare module 'jest-extended/dist/matchers/toInclude/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toInclude/predicate'>;
}
declare module 'jest-extended/dist/matchers/toIncludeAllMembers/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toIncludeAllMembers/index'>;
}
declare module 'jest-extended/dist/matchers/toIncludeAllMembers/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toIncludeAllMembers/predicate'>;
}
declare module 'jest-extended/dist/matchers/toIncludeAnyMembers/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toIncludeAnyMembers/index'>;
}
declare module 'jest-extended/dist/matchers/toIncludeAnyMembers/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toIncludeAnyMembers/predicate'>;
}
declare module 'jest-extended/dist/matchers/toIncludeMultiple/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toIncludeMultiple/index'>;
}
declare module 'jest-extended/dist/matchers/toIncludeMultiple/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toIncludeMultiple/predicate'>;
}
declare module 'jest-extended/dist/matchers/toIncludeRepeated/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toIncludeRepeated/index'>;
}
declare module 'jest-extended/dist/matchers/toIncludeRepeated/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toIncludeRepeated/predicate'>;
}
declare module 'jest-extended/dist/matchers/toIncludeSameMembers/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toIncludeSameMembers/index'>;
}
declare module 'jest-extended/dist/matchers/toIncludeSameMembers/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toIncludeSameMembers/predicate'>;
}
declare module 'jest-extended/dist/matchers/toReject/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toReject/index'>;
}
declare module 'jest-extended/dist/matchers/toReject/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toReject/predicate'>;
}
declare module 'jest-extended/dist/matchers/toResolve/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toResolve/index'>;
}
declare module 'jest-extended/dist/matchers/toResolve/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toResolve/predicate'>;
}
declare module 'jest-extended/dist/matchers/toSatisfy/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toSatisfy/index'>;
}
declare module 'jest-extended/dist/matchers/toSatisfyAll/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toSatisfyAll/index'>;
}
declare module 'jest-extended/dist/matchers/toSatisfyAll/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toSatisfyAll/predicate'>;
}
declare module 'jest-extended/dist/matchers/toStartWith/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toStartWith/index'>;
}
declare module 'jest-extended/dist/matchers/toStartWith/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toStartWith/predicate'>;
}
declare module 'jest-extended/dist/matchers/toThrowWithMessage/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toThrowWithMessage/index'>;
}
declare module 'jest-extended/dist/matchers/toThrowWithMessage/predicate.js' {
  declare module.exports: $Exports<'jest-extended/dist/matchers/toThrowWithMessage/predicate'>;
}
declare module 'jest-extended/dist/utils/index.js' {
  declare module.exports: $Exports<'jest-extended/dist/utils/index'>;
}
