// flow-typed signature: b5ba5b1bff34b021384d0eb8b9ced507
// flow-typed version: <<STUB>>/react-testing-library_v^6.0.0/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-testing-library'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-testing-library' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-testing-library/cleanup-after-each' {
  declare module.exports: any;
}

declare module 'react-testing-library/dist/__mocks__/axios' {
  declare module.exports: any;
}

declare module 'react-testing-library/dist/__tests__/act' {
  declare module.exports: any;
}

declare module 'react-testing-library/dist/__tests__/bugs' {
  declare module.exports: any;
}

declare module 'react-testing-library/dist/__tests__/debug' {
  declare module.exports: any;
}

declare module 'react-testing-library/dist/__tests__/end-to-end' {
  declare module.exports: any;
}

declare module 'react-testing-library/dist/__tests__/events' {
  declare module.exports: any;
}

declare module 'react-testing-library/dist/__tests__/fetch' {
  declare module.exports: any;
}

declare module 'react-testing-library/dist/__tests__/forms' {
  declare module.exports: any;
}

declare module 'react-testing-library/dist/__tests__/no-act' {
  declare module.exports: any;
}

declare module 'react-testing-library/dist/__tests__/render' {
  declare module.exports: any;
}

declare module 'react-testing-library/dist/__tests__/rerender' {
  declare module.exports: any;
}

declare module 'react-testing-library/dist/__tests__/stopwatch' {
  declare module.exports: any;
}

declare module 'react-testing-library/dist/act-compat' {
  declare module.exports: any;
}

declare module 'react-testing-library/dist/index' {
  declare module.exports: any;
}

declare module 'react-testing-library/dist/react-testing-library.cjs' {
  declare module.exports: any;
}

declare module 'react-testing-library/dist/react-testing-library.esm' {
  declare module.exports: any;
}

declare module 'react-testing-library/dist/react-testing-library.umd' {
  declare module.exports: any;
}

declare module 'react-testing-library/dist/react-testing-library.umd.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-testing-library/cleanup-after-each.js' {
  declare module.exports: $Exports<'react-testing-library/cleanup-after-each'>;
}
declare module 'react-testing-library/dist/__mocks__/axios.js' {
  declare module.exports: $Exports<'react-testing-library/dist/__mocks__/axios'>;
}
declare module 'react-testing-library/dist/__tests__/act.js' {
  declare module.exports: $Exports<'react-testing-library/dist/__tests__/act'>;
}
declare module 'react-testing-library/dist/__tests__/bugs.js' {
  declare module.exports: $Exports<'react-testing-library/dist/__tests__/bugs'>;
}
declare module 'react-testing-library/dist/__tests__/debug.js' {
  declare module.exports: $Exports<'react-testing-library/dist/__tests__/debug'>;
}
declare module 'react-testing-library/dist/__tests__/end-to-end.js' {
  declare module.exports: $Exports<'react-testing-library/dist/__tests__/end-to-end'>;
}
declare module 'react-testing-library/dist/__tests__/events.js' {
  declare module.exports: $Exports<'react-testing-library/dist/__tests__/events'>;
}
declare module 'react-testing-library/dist/__tests__/fetch.js' {
  declare module.exports: $Exports<'react-testing-library/dist/__tests__/fetch'>;
}
declare module 'react-testing-library/dist/__tests__/forms.js' {
  declare module.exports: $Exports<'react-testing-library/dist/__tests__/forms'>;
}
declare module 'react-testing-library/dist/__tests__/no-act.js' {
  declare module.exports: $Exports<'react-testing-library/dist/__tests__/no-act'>;
}
declare module 'react-testing-library/dist/__tests__/render.js' {
  declare module.exports: $Exports<'react-testing-library/dist/__tests__/render'>;
}
declare module 'react-testing-library/dist/__tests__/rerender.js' {
  declare module.exports: $Exports<'react-testing-library/dist/__tests__/rerender'>;
}
declare module 'react-testing-library/dist/__tests__/stopwatch.js' {
  declare module.exports: $Exports<'react-testing-library/dist/__tests__/stopwatch'>;
}
declare module 'react-testing-library/dist/act-compat.js' {
  declare module.exports: $Exports<'react-testing-library/dist/act-compat'>;
}
declare module 'react-testing-library/dist/index.js' {
  declare module.exports: $Exports<'react-testing-library/dist/index'>;
}
declare module 'react-testing-library/dist/react-testing-library.cjs.js' {
  declare module.exports: $Exports<'react-testing-library/dist/react-testing-library.cjs'>;
}
declare module 'react-testing-library/dist/react-testing-library.esm.js' {
  declare module.exports: $Exports<'react-testing-library/dist/react-testing-library.esm'>;
}
declare module 'react-testing-library/dist/react-testing-library.umd.js' {
  declare module.exports: $Exports<'react-testing-library/dist/react-testing-library.umd'>;
}
declare module 'react-testing-library/dist/react-testing-library.umd.min.js' {
  declare module.exports: $Exports<'react-testing-library/dist/react-testing-library.umd.min'>;
}
