// flow-typed signature: 098f6e71e4534c0dc6453124b3a69699
// flow-typed version: <<STUB>>/storybook-readme_v^4.0.5/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'storybook-readme'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'storybook-readme' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'storybook-readme/components/Marked' {
  declare module.exports: any;
}

declare module 'storybook-readme/components/ReadmePanel' {
  declare module.exports: any;
}

declare module 'storybook-readme/constants' {
  declare module.exports: any;
}

declare module 'storybook-readme/env/common/index' {
  declare module.exports: any;
}

declare module 'storybook-readme/env/react/components/FooterDocs' {
  declare module.exports: any;
}

declare module 'storybook-readme/env/react/components/StoryPreview' {
  declare module.exports: any;
}

declare module 'storybook-readme/env/react/index' {
  declare module.exports: any;
}

declare module 'storybook-readme/env/vue/components/FooterDocs' {
  declare module.exports: any;
}

declare module 'storybook-readme/env/vue/components/MarkdownContainer' {
  declare module.exports: any;
}

declare module 'storybook-readme/env/vue/components/Story' {
  declare module.exports: any;
}

declare module 'storybook-readme/env/vue/components/StoryPreview' {
  declare module.exports: any;
}

declare module 'storybook-readme/env/vue/docs-loader' {
  declare module.exports: any;
}

declare module 'storybook-readme/env/vue/index' {
  declare module.exports: any;
}

declare module 'storybook-readme/env/vue/updateWebpackConfig' {
  declare module.exports: any;
}

declare module 'storybook-readme/register' {
  declare module.exports: any;
}

declare module 'storybook-readme/services/docsManager' {
  declare module.exports: any;
}

declare module 'storybook-readme/services/highlite' {
  declare module.exports: any;
}

declare module 'storybook-readme/services/marked' {
  declare module.exports: any;
}

declare module 'storybook-readme/services/normalizeDocs' {
  declare module.exports: any;
}

declare module 'storybook-readme/services/transformEmojis' {
  declare module.exports: any;
}

declare module 'storybook-readme/src/constants' {
  declare module.exports: any;
}

declare module 'storybook-readme/src/env/common/index' {
  declare module.exports: any;
}

declare module 'storybook-readme/src/env/react/index' {
  declare module.exports: any;
}

declare module 'storybook-readme/src/env/vue/index' {
  declare module.exports: any;
}

declare module 'storybook-readme/src/index' {
  declare module.exports: any;
}

declare module 'storybook-readme/src/register' {
  declare module.exports: any;
}

declare module 'storybook-readme/src/with-docs' {
  declare module.exports: any;
}

declare module 'storybook-readme/src/with-readme' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/github-markdown-css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/prism-theme-css' {
  declare module.exports: any;
}

declare module 'storybook-readme/with-docs' {
  declare module.exports: any;
}

declare module 'storybook-readme/with-readme' {
  declare module.exports: any;
}

// Filename aliases
declare module 'storybook-readme/components/Marked.js' {
  declare module.exports: $Exports<'storybook-readme/components/Marked'>;
}
declare module 'storybook-readme/components/ReadmePanel.js' {
  declare module.exports: $Exports<'storybook-readme/components/ReadmePanel'>;
}
declare module 'storybook-readme/constants.js' {
  declare module.exports: $Exports<'storybook-readme/constants'>;
}
declare module 'storybook-readme/env/common/index.js' {
  declare module.exports: $Exports<'storybook-readme/env/common/index'>;
}
declare module 'storybook-readme/env/react/components/FooterDocs.js' {
  declare module.exports: $Exports<'storybook-readme/env/react/components/FooterDocs'>;
}
declare module 'storybook-readme/env/react/components/StoryPreview.js' {
  declare module.exports: $Exports<'storybook-readme/env/react/components/StoryPreview'>;
}
declare module 'storybook-readme/env/react/index.js' {
  declare module.exports: $Exports<'storybook-readme/env/react/index'>;
}
declare module 'storybook-readme/env/vue/components/FooterDocs.js' {
  declare module.exports: $Exports<'storybook-readme/env/vue/components/FooterDocs'>;
}
declare module 'storybook-readme/env/vue/components/MarkdownContainer.js' {
  declare module.exports: $Exports<'storybook-readme/env/vue/components/MarkdownContainer'>;
}
declare module 'storybook-readme/env/vue/components/Story.js' {
  declare module.exports: $Exports<'storybook-readme/env/vue/components/Story'>;
}
declare module 'storybook-readme/env/vue/components/StoryPreview.js' {
  declare module.exports: $Exports<'storybook-readme/env/vue/components/StoryPreview'>;
}
declare module 'storybook-readme/env/vue/docs-loader.js' {
  declare module.exports: $Exports<'storybook-readme/env/vue/docs-loader'>;
}
declare module 'storybook-readme/env/vue/index.js' {
  declare module.exports: $Exports<'storybook-readme/env/vue/index'>;
}
declare module 'storybook-readme/env/vue/updateWebpackConfig.js' {
  declare module.exports: $Exports<'storybook-readme/env/vue/updateWebpackConfig'>;
}
declare module 'storybook-readme/index' {
  declare module.exports: $Exports<'storybook-readme'>;
}
declare module 'storybook-readme/index.js' {
  declare module.exports: $Exports<'storybook-readme'>;
}
declare module 'storybook-readme/register.js' {
  declare module.exports: $Exports<'storybook-readme/register'>;
}
declare module 'storybook-readme/services/docsManager.js' {
  declare module.exports: $Exports<'storybook-readme/services/docsManager'>;
}
declare module 'storybook-readme/services/highlite.js' {
  declare module.exports: $Exports<'storybook-readme/services/highlite'>;
}
declare module 'storybook-readme/services/marked.js' {
  declare module.exports: $Exports<'storybook-readme/services/marked'>;
}
declare module 'storybook-readme/services/normalizeDocs.js' {
  declare module.exports: $Exports<'storybook-readme/services/normalizeDocs'>;
}
declare module 'storybook-readme/services/transformEmojis.js' {
  declare module.exports: $Exports<'storybook-readme/services/transformEmojis'>;
}
declare module 'storybook-readme/src/constants.js' {
  declare module.exports: $Exports<'storybook-readme/src/constants'>;
}
declare module 'storybook-readme/src/env/common/index.js' {
  declare module.exports: $Exports<'storybook-readme/src/env/common/index'>;
}
declare module 'storybook-readme/src/env/react/index.js' {
  declare module.exports: $Exports<'storybook-readme/src/env/react/index'>;
}
declare module 'storybook-readme/src/env/vue/index.js' {
  declare module.exports: $Exports<'storybook-readme/src/env/vue/index'>;
}
declare module 'storybook-readme/src/index.js' {
  declare module.exports: $Exports<'storybook-readme/src/index'>;
}
declare module 'storybook-readme/src/register.js' {
  declare module.exports: $Exports<'storybook-readme/src/register'>;
}
declare module 'storybook-readme/src/with-docs.js' {
  declare module.exports: $Exports<'storybook-readme/src/with-docs'>;
}
declare module 'storybook-readme/src/with-readme.js' {
  declare module.exports: $Exports<'storybook-readme/src/with-readme'>;
}
declare module 'storybook-readme/styles/github-markdown-css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/github-markdown-css'>;
}
declare module 'storybook-readme/styles/prism-theme-css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/prism-theme-css'>;
}
declare module 'storybook-readme/with-docs.js' {
  declare module.exports: $Exports<'storybook-readme/with-docs'>;
}
declare module 'storybook-readme/with-readme.js' {
  declare module.exports: $Exports<'storybook-readme/with-readme'>;
}
