// flow-typed signature: ff8f72f5d9c1b535be507280d4973143
// flow-typed version: <<STUB>>/@babel/helper-builder-react-jsx_v^7.12.13/flow_v0.110.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/helper-builder-react-jsx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/helper-builder-react-jsx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/helper-builder-react-jsx/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/helper-builder-react-jsx/lib/index' {
  declare module.exports: $Exports<'@babel/helper-builder-react-jsx/lib'>;
}
declare module '@babel/helper-builder-react-jsx/lib/index.js' {
  declare module.exports: $Exports<'@babel/helper-builder-react-jsx/lib'>;
}
