// flow-typed signature: c9ddaf69fae1a51644ad05a2eb3b6c88
// flow-typed version: <<STUB>>/@babel/helper-builder-react-jsx-experimental_v^7.12.11/flow_v0.110.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/helper-builder-react-jsx-experimental'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/helper-builder-react-jsx-experimental' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/helper-builder-react-jsx-experimental/lib' {
  declare module.exports: any;
}

declare module '@babel/helper-builder-react-jsx-experimental/src' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/helper-builder-react-jsx-experimental/lib/index' {
  declare module.exports: $Exports<'@babel/helper-builder-react-jsx-experimental/lib'>;
}
declare module '@babel/helper-builder-react-jsx-experimental/lib/index.js' {
  declare module.exports: $Exports<'@babel/helper-builder-react-jsx-experimental/lib'>;
}
declare module '@babel/helper-builder-react-jsx-experimental/src/index' {
  declare module.exports: $Exports<'@babel/helper-builder-react-jsx-experimental/src'>;
}
declare module '@babel/helper-builder-react-jsx-experimental/src/index.js' {
  declare module.exports: $Exports<'@babel/helper-builder-react-jsx-experimental/src'>;
}
