// flow-typed signature: cfd8538df7470874c38e84cd855373d3
// flow-typed version: <<STUB>>/@testing-library/react_v^8.0.1/flow_v0.102.0-rc

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@testing-library/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@testing-library/react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@testing-library/react/cleanup-after-each' {
  declare module.exports: any;
}

declare module '@testing-library/react/dist/__mocks__/axios' {
  declare module.exports: any;
}

declare module '@testing-library/react/dist/__tests__/act' {
  declare module.exports: any;
}

declare module '@testing-library/react/dist/__tests__/bugs' {
  declare module.exports: any;
}

declare module '@testing-library/react/dist/__tests__/debug' {
  declare module.exports: any;
}

declare module '@testing-library/react/dist/__tests__/end-to-end' {
  declare module.exports: any;
}

declare module '@testing-library/react/dist/__tests__/events' {
  declare module.exports: any;
}

declare module '@testing-library/react/dist/__tests__/fetch' {
  declare module.exports: any;
}

declare module '@testing-library/react/dist/__tests__/forms' {
  declare module.exports: any;
}

declare module '@testing-library/react/dist/__tests__/no-act' {
  declare module.exports: any;
}

declare module '@testing-library/react/dist/__tests__/old-act' {
  declare module.exports: any;
}

declare module '@testing-library/react/dist/__tests__/render' {
  declare module.exports: any;
}

declare module '@testing-library/react/dist/__tests__/rerender' {
  declare module.exports: any;
}

declare module '@testing-library/react/dist/__tests__/stopwatch' {
  declare module.exports: any;
}

declare module '@testing-library/react/dist/@testing-library/react.cjs' {
  declare module.exports: any;
}

declare module '@testing-library/react/dist/@testing-library/react.esm' {
  declare module.exports: any;
}

declare module '@testing-library/react/dist/@testing-library/react.umd' {
  declare module.exports: any;
}

declare module '@testing-library/react/dist/@testing-library/react.umd.min' {
  declare module.exports: any;
}

declare module '@testing-library/react/dist/act-compat' {
  declare module.exports: any;
}

declare module '@testing-library/react/dist/index' {
  declare module.exports: any;
}

declare module '@testing-library/react/dist/react-dom-16.9.0-is-released' {
  declare module.exports: any;
}

// Filename aliases
declare module '@testing-library/react/cleanup-after-each.js' {
  declare module.exports: $Exports<'@testing-library/react/cleanup-after-each'>;
}
declare module '@testing-library/react/dist/__mocks__/axios.js' {
  declare module.exports: $Exports<'@testing-library/react/dist/__mocks__/axios'>;
}
declare module '@testing-library/react/dist/__tests__/act.js' {
  declare module.exports: $Exports<'@testing-library/react/dist/__tests__/act'>;
}
declare module '@testing-library/react/dist/__tests__/bugs.js' {
  declare module.exports: $Exports<'@testing-library/react/dist/__tests__/bugs'>;
}
declare module '@testing-library/react/dist/__tests__/debug.js' {
  declare module.exports: $Exports<'@testing-library/react/dist/__tests__/debug'>;
}
declare module '@testing-library/react/dist/__tests__/end-to-end.js' {
  declare module.exports: $Exports<'@testing-library/react/dist/__tests__/end-to-end'>;
}
declare module '@testing-library/react/dist/__tests__/events.js' {
  declare module.exports: $Exports<'@testing-library/react/dist/__tests__/events'>;
}
declare module '@testing-library/react/dist/__tests__/fetch.js' {
  declare module.exports: $Exports<'@testing-library/react/dist/__tests__/fetch'>;
}
declare module '@testing-library/react/dist/__tests__/forms.js' {
  declare module.exports: $Exports<'@testing-library/react/dist/__tests__/forms'>;
}
declare module '@testing-library/react/dist/__tests__/no-act.js' {
  declare module.exports: $Exports<'@testing-library/react/dist/__tests__/no-act'>;
}
declare module '@testing-library/react/dist/__tests__/old-act.js' {
  declare module.exports: $Exports<'@testing-library/react/dist/__tests__/old-act'>;
}
declare module '@testing-library/react/dist/__tests__/render.js' {
  declare module.exports: $Exports<'@testing-library/react/dist/__tests__/render'>;
}
declare module '@testing-library/react/dist/__tests__/rerender.js' {
  declare module.exports: $Exports<'@testing-library/react/dist/__tests__/rerender'>;
}
declare module '@testing-library/react/dist/__tests__/stopwatch.js' {
  declare module.exports: $Exports<'@testing-library/react/dist/__tests__/stopwatch'>;
}
declare module '@testing-library/react/dist/@testing-library/react.cjs.js' {
  declare module.exports: $Exports<'@testing-library/react/dist/@testing-library/react.cjs'>;
}
declare module '@testing-library/react/dist/@testing-library/react.esm.js' {
  declare module.exports: $Exports<'@testing-library/react/dist/@testing-library/react.esm'>;
}
declare module '@testing-library/react/dist/@testing-library/react.umd.js' {
  declare module.exports: $Exports<'@testing-library/react/dist/@testing-library/react.umd'>;
}
declare module '@testing-library/react/dist/@testing-library/react.umd.min.js' {
  declare module.exports: $Exports<'@testing-library/react/dist/@testing-library/react.umd.min'>;
}
declare module '@testing-library/react/dist/act-compat.js' {
  declare module.exports: $Exports<'@testing-library/react/dist/act-compat'>;
}
declare module '@testing-library/react/dist/index.js' {
  declare module.exports: $Exports<'@testing-library/react/dist/index'>;
}
declare module '@testing-library/react/dist/react-dom-16.9.0-is-released.js' {
  declare module.exports: $Exports<'@testing-library/react/dist/react-dom-16.9.0-is-released'>;
}
