// flow-typed signature: 972ffe6abfe3c94393bfac8a38d159d7
// flow-typed version: <<STUB>>/@storybook/addon-actions_v^5.0.9/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-actions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-actions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-actions/dist/components/ActionLogger/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/components/ActionLogger/style' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/constants' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/containers/ActionLogger/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/manager' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/preview/__tests__/action.test' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/preview/__tests__/configureActions.test' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/preview/action' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/preview/actions' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/preview/configureActions' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/preview/decorateAction' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/preview/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/preview/withActions' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/src/components/ActionLogger/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/src/components/ActionLogger/style' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/src/constants' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/src/containers/ActionLogger/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/src/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/src/manager' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/src/preview/__tests__/action.test' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/src/preview/__tests__/configureActions.test' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/src/preview/action' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/src/preview/actions' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/src/preview/configureActions' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/src/preview/decorateAction' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/src/preview/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/src/preview/withActions' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-actions/dist/components/ActionLogger/index.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/components/ActionLogger/index'>;
}
declare module '@storybook/addon-actions/dist/components/ActionLogger/style.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/components/ActionLogger/style'>;
}
declare module '@storybook/addon-actions/dist/constants.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/constants'>;
}
declare module '@storybook/addon-actions/dist/containers/ActionLogger/index.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/containers/ActionLogger/index'>;
}
declare module '@storybook/addon-actions/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/index'>;
}
declare module '@storybook/addon-actions/dist/manager.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/manager'>;
}
declare module '@storybook/addon-actions/dist/preview/__tests__/action.test.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/preview/__tests__/action.test'>;
}
declare module '@storybook/addon-actions/dist/preview/__tests__/configureActions.test.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/preview/__tests__/configureActions.test'>;
}
declare module '@storybook/addon-actions/dist/preview/action.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/preview/action'>;
}
declare module '@storybook/addon-actions/dist/preview/actions.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/preview/actions'>;
}
declare module '@storybook/addon-actions/dist/preview/configureActions.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/preview/configureActions'>;
}
declare module '@storybook/addon-actions/dist/preview/decorateAction.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/preview/decorateAction'>;
}
declare module '@storybook/addon-actions/dist/preview/index.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/preview/index'>;
}
declare module '@storybook/addon-actions/dist/preview/withActions.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/preview/withActions'>;
}
declare module '@storybook/addon-actions/register.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/register'>;
}
declare module '@storybook/addon-actions/src/components/ActionLogger/index.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/src/components/ActionLogger/index'>;
}
declare module '@storybook/addon-actions/src/components/ActionLogger/style.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/src/components/ActionLogger/style'>;
}
declare module '@storybook/addon-actions/src/constants.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/src/constants'>;
}
declare module '@storybook/addon-actions/src/containers/ActionLogger/index.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/src/containers/ActionLogger/index'>;
}
declare module '@storybook/addon-actions/src/index.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/src/index'>;
}
declare module '@storybook/addon-actions/src/manager.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/src/manager'>;
}
declare module '@storybook/addon-actions/src/preview/__tests__/action.test.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/src/preview/__tests__/action.test'>;
}
declare module '@storybook/addon-actions/src/preview/__tests__/configureActions.test.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/src/preview/__tests__/configureActions.test'>;
}
declare module '@storybook/addon-actions/src/preview/action.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/src/preview/action'>;
}
declare module '@storybook/addon-actions/src/preview/actions.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/src/preview/actions'>;
}
declare module '@storybook/addon-actions/src/preview/configureActions.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/src/preview/configureActions'>;
}
declare module '@storybook/addon-actions/src/preview/decorateAction.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/src/preview/decorateAction'>;
}
declare module '@storybook/addon-actions/src/preview/index.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/src/preview/index'>;
}
declare module '@storybook/addon-actions/src/preview/withActions.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/src/preview/withActions'>;
}
