// flow-typed signature: 84fd1ad4e747a4e3b7ad357f26406a13
// flow-typed version: <<STUB>>/@storybook/addon-controls_v^6.1.21/flow_v0.110.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-controls'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-controls' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-controls/dist/components/ControlsPanel' {
  declare module.exports: any;
}

declare module '@storybook/addon-controls/dist/components/NoControlsWarning' {
  declare module.exports: any;
}

declare module '@storybook/addon-controls/dist/constants' {
  declare module.exports: any;
}

declare module '@storybook/addon-controls/dist' {
  declare module.exports: any;
}

declare module '@storybook/addon-controls/dist/preset/ensureDocsBeforeControls' {
  declare module.exports: any;
}

declare module '@storybook/addon-controls/dist/preset' {
  declare module.exports: any;
}

declare module '@storybook/addon-controls/dist/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-controls/dist/title' {
  declare module.exports: any;
}

declare module '@storybook/addon-controls/preset' {
  declare module.exports: any;
}

declare module '@storybook/addon-controls/register' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-controls/dist/components/ControlsPanel.js' {
  declare module.exports: $Exports<'@storybook/addon-controls/dist/components/ControlsPanel'>;
}
declare module '@storybook/addon-controls/dist/components/NoControlsWarning.js' {
  declare module.exports: $Exports<'@storybook/addon-controls/dist/components/NoControlsWarning'>;
}
declare module '@storybook/addon-controls/dist/constants.js' {
  declare module.exports: $Exports<'@storybook/addon-controls/dist/constants'>;
}
declare module '@storybook/addon-controls/dist/index' {
  declare module.exports: $Exports<'@storybook/addon-controls/dist'>;
}
declare module '@storybook/addon-controls/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addon-controls/dist'>;
}
declare module '@storybook/addon-controls/dist/preset/ensureDocsBeforeControls.js' {
  declare module.exports: $Exports<'@storybook/addon-controls/dist/preset/ensureDocsBeforeControls'>;
}
declare module '@storybook/addon-controls/dist/preset/index' {
  declare module.exports: $Exports<'@storybook/addon-controls/dist/preset'>;
}
declare module '@storybook/addon-controls/dist/preset/index.js' {
  declare module.exports: $Exports<'@storybook/addon-controls/dist/preset'>;
}
declare module '@storybook/addon-controls/dist/register.js' {
  declare module.exports: $Exports<'@storybook/addon-controls/dist/register'>;
}
declare module '@storybook/addon-controls/dist/title.js' {
  declare module.exports: $Exports<'@storybook/addon-controls/dist/title'>;
}
declare module '@storybook/addon-controls/preset.js' {
  declare module.exports: $Exports<'@storybook/addon-controls/preset'>;
}
declare module '@storybook/addon-controls/register.js' {
  declare module.exports: $Exports<'@storybook/addon-controls/register'>;
}
